"""empty message

Revision ID: 17709e547a1b
Revises: 3c1af17b35dc
Create Date: 2022-06-03 02:26:55.367460

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '17709e547a1b'
down_revision = '3c1af17b35dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('product', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'updated_at')
    op.drop_column('product', 'created_at')
    # ### end Alembic commands ###
