"""Fix

Revision ID: 52e9b2209fda
Revises: 3e9e6f7687c8
Create Date: 2022-05-31 12:06:28.571934

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '52e9b2209fda'
down_revision = '3e9e6f7687c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_follows',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('followee_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['followee_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.UniqueConstraint('user_id', 'followee_id', name='user_followee_unique')
                    )
    op.add_column('product', sa.Column('sold', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'sold')
    op.drop_table('user_follows')
    # ### end Alembic commands ###
